"""empty message

Revision ID: 36e1680625df
Revises: 
Create Date: 2018-07-16 18:30:18.864477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e1680625df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wikipedia_suggest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('wikipedia_page_id', sa.BigInteger(), nullable=True),
    sa.Column('wikipedia_page_title', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wikipedia_suggest')
    # ### end Alembic commands ###
